[package]
name = "picosat"
version = "0.1.0"
authors = ["Jeremy DeJournett <jcdejournett@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
